apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: it-diagnostics
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scrape the auth-service
      - job_name: 'auth-service'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
            action: keep
            regex: it-diagnostics;auth-service
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
          - source_labels: [__address__]
            action: replace
            regex: (.+):\d+
            replacement: ${1}:5000
            target_label: __address__

      # Scrape the case-service
      - job_name: 'case-service'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
            action: keep
            regex: it-diagnostics;case-service
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
          - source_labels: [__address__]
            action: replace
            regex: (.+):\d+
            replacement: ${1}:5001
            target_label: __address__

      # Scrape the diagnostic-service
      - job_name: 'diagnostic-service'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_pod_label_app]
            action: keep
            regex: it-diagnostics;diagnostic-service
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
          - source_labels: [__address__]
            action: replace
            regex: (.+):\d+
            replacement: ${1}:5002
            target_label: __address__

