apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: it-diagnostics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: maxmedov/it-diagnostics-management-platform:frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_AUTH_SERVICE_URL
          value: "/auth"
        - name: REACT_APP_CASE_SERVICE_URL
          value: "/case"
        - name: REACT_APP_DIAGNOSTIC_SERVICE_URL
          value: "/diagnostic"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: it-diagnostics
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend

