apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: it-diagnostics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: it-diagnostics-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: it-diagnostics-config
              key: POSTGRES_DB
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: it-diagnostics
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres

