apiVersion: v1
kind: Secret
metadata:
  name: it-diagnostics-secret
  namespace: it-diagnostics
type: Opaque
stringData:
  POSTGRES_PASSWORD: "yourpassword"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: it-diagnostics-config
  namespace: it-diagnostics
data:
  POSTGRES_DB: "itdiagnostics"

